//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.0
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveSplit {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebFiles() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LiveSplit.WebFiles", typeof(WebFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die /*
        /// FastClick: polyfill to remove click delays on browsers with touch UIs.
        ///
        /// @version 1.0.3
        /// @codingstandard ftlabs-jsv2
        /// @copyright The Financial Times Limited [All Rights Reserved]
        /// @license MIT License (see LICENSE.txt)
        ///*/
        ///(function e$$0(g,m,b){function h(f,k){if(!m[f]){if(!g[f]){var a=&quot;function&quot;==typeof require&amp;&amp;require;if(!k&amp;&amp;a)return a(f,!0);if(e)return e(f,!0);a=Error(&quot;Cannot find module &apos;&quot;+f+&quot;&apos;&quot;);throw a.code=&quot;MODULE_NOT_FOUND&quot;,a;}a=m[f]={exports:{}};g[f][0].call(a.exports,function(a){var d= [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string fastclick_min_js {
            get {
                return ResourceManager.GetString("fastclick_min_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die /*! @source http://purl.eligrey.com/github/FileSaver.js/blob/master/FileSaver.js */
        ///var saveAs=saveAs||&quot;undefined&quot;!=typeof navigator&amp;&amp;navigator.msSaveOrOpenBlob&amp;&amp;navigator.msSaveOrOpenBlob.bind(navigator)||function(e){&quot;use strict&quot;;if(&quot;undefined&quot;==typeof navigator||!/MSIE [1-9]\./.test(navigator.userAgent)){var t=e.document,n=function(){return e.URL||e.webkitURL||e},o=t.createElementNS(&quot;http://www.w3.org/1999/xhtml&quot;,&quot;a&quot;),r=&quot;download&quot;in o,i=function(n){var o=t.createEvent(&quot;MouseEvents&quot;);o.initMouseEvent(&quot;cli [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string FileSaver_min_js {
            get {
                return ResourceManager.GetString("FileSaver_min_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        /// </summary>
        internal static System.Drawing.Icon Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE html&gt;
        ///&lt;html manifest=&quot;webstorage.manifest&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;RTA Timer&lt;/title&gt;
        ///	&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;/&gt;
        ///	&lt;!-- Mobile Support kinda, prevents zooming --&gt;
        ///	&lt;meta name=&quot;viewport&quot; content=&quot;height = 400, width = 215, user-scalable = no&quot; /&gt;
        ///	&lt;meta name=&quot;apple-mobile-web-app-capable&quot; content=&quot;yes&quot; /&gt;
        ///	&lt;meta name=&quot;apple-mobile-web-app-title&quot; content=&quot;WebSplit&quot; /&gt;
        ///	&lt;meta name=&quot;apple-mobile-web-app-status-bar-style&quot; content=&quot;black&quot; /&gt;
        ///	&lt;meta name=&quot;format- [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string index_html {
            get {
                return ResourceManager.GetString("index_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die !function(t){if(&quot;object&quot;==typeof exports&amp;&amp;&quot;undefined&quot;!=typeof module)module.exports=t();else if(&quot;function&quot;==typeof define&amp;&amp;define.amd)define([],t);else{var e;&quot;undefined&quot;!=typeof window?e=window:&quot;undefined&quot;!=typeof global?e=global:&quot;undefined&quot;!=typeof self&amp;&amp;(e=self),e.Slideout=t()}}(function(){var t,e,n;return function i(t,e,n){function o(s,a){if(!e[s]){if(!t[s]){var u=typeof require==&quot;function&quot;&amp;&amp;require;if(!a&amp;&amp;u)return u(s,!0);if(r)return r(s,!0);var f=new Error(&quot;Cannot find module &apos;&quot;+s+&quot;&apos;&quot;);throw f.code=&quot;MO [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string slideout_min_js {
            get {
                return ResourceManager.GetString("slideout_min_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die * { margin:0; padding:0; }
        ///html {
        ///    -ms-touch-action: manipulation;
        ///    touch-action: manipulation;
        ///}
        ///
        ///body {
        ///	font-family: Segoe UI,Frutiger,Frutiger Linotype,Dejavu Sans,Helvetica Neue,Arial,sans-serif;
        ///	background-color: black;
        ///	color: white;
        ///	width: 100%;
        ///	height: 100%;
        ///}
        ///
        ///.slideout-menu {
        ///  position: fixed;
        ///  left: 0;
        ///  top: 0;
        ///  bottom: 0;
        ///  right: 0;
        ///  z-index: 0;
        ///  width: 123px;
        ///  overflow-y: auto;
        ///  -webkit-overflow-scrolling: touch;
        ///  display: none;
        ///  background-color: # [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string timer_css {
            get {
                return ResourceManager.GetString("timer_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die // The majority of the code (not related to splitting functions or anything else
        ///// that looks like spaghetti code) was originally written by Ian &quot;bmn&quot; Bennett,
        ///// from http://www.w00ty.com/sda/timer/
        /////
        /////
        ///// Shoutouts to him, I probably couldn&apos;t have built everything from scratch
        ///// - iotku
        ///
        ///function GameTimer(d) {
        ///    /* User configurable settings */
        ///    this.maxSplits = 10;   // Max splits to display at once
        ///    
        ///    /* Timer variables (do not change unless you&apos;re sure) */
        ///    this.currentS [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string timer_js {
            get {
                return ResourceManager.GetString("timer_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CACHE MANIFEST
        ///
        ///CACHE:
        ///index.html
        ///js/FileSaver.min.js
        ///js/fastclick-min.js
        ///js/slideout.min.js
        ///js/timer.js
        ///css/timer.css ähnelt.
        /// </summary>
        internal static string webstorage_manifest {
            get {
                return ResourceManager.GetString("webstorage_manifest", resourceCulture);
            }
        }
    }
}
